# Generated by Django 4.2 on 2026-06-05 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('leads', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('generated_content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_drafts', to='clients.client')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_drafts', to='leads.lead')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_drafts', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('lead', 'Lead'), ('client', 'Client'), ('project', 'Project'), ('task', 'Task'), ('invoice', 'Invoice')], max_length=30)),
                ('entity_id', models.PositiveIntegerField()),
                ('prediction_type', models.CharField(choices=[('lead_score', 'Lead score'), ('churn_risk', 'Churn risk'), ('payment_risk', 'Payment risk'), ('project_risk', 'Project risk'), ('task_delay', 'Task delay')], max_length=50)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('probability', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('sales', 'Sales'), ('client', 'Client'), ('project', 'Project'), ('billing', 'Billing'), ('productivity', 'Productivity')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('recommendation', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='proposaldraft',
            index=models.Index(fields=['user', 'status', 'created_at'], name='ai_engine_p_user_id_b3b539_idx'),
        ),
        migrations.AddIndex(
            model_name='proposaldraft',
            index=models.Index(fields=['client', 'created_at'], name='ai_engine_p_client__858aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='proposaldraft',
            index=models.Index(fields=['lead', 'created_at'], name='ai_engine_p_lead_id_034bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='proposaldraft',
            index=models.Index(fields=['project', 'created_at'], name='ai_engine_p_project_fdbbbf_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprediction',
            index=models.Index(fields=['user', 'entity_type', 'entity_id'], name='ai_engine_a_user_id_92559f_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprediction',
            index=models.Index(fields=['user', 'prediction_type', 'created_at'], name='ai_engine_a_user_id_da8d61_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='ai_engine_a_user_id_9f8832_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['user', 'category', 'severity'], name='ai_engine_a_user_id_6bfa26_idx'),
        ),
    ]
