# Generated by Django 4.2 on 2026-06-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldraft',
            name='client_problem',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='estimated_timeline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='proposal_type',
            field=models.CharField(choices=[('service', 'Service'), ('project', 'Project'), ('retainer', 'Retainer'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='proposed_solution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='services_offered',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='proposaldraft',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
