# Generated by Django 4.2 on 2026-06-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_proposaldraft_client_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='source_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='category',
            field=models.CharField(choices=[('lead', 'Lead'), ('client', 'Client'), ('invoice', 'Invoice'), ('project', 'Project'), ('task', 'Task'), ('revenue', 'Revenue'), ('workflow', 'Workflow'), ('system', 'System'), ('sales', 'Sales'), ('billing', 'Billing'), ('productivity', 'Productivity')], max_length=30),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('critical', 'Critical'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='info', max_length=20),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['user', 'source_type', 'source_id', 'category'], name='ai_engine_a_user_id_eb8fb5_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiinsight',
            constraint=models.UniqueConstraint(fields=('user', 'source_type', 'source_id', 'category', 'title'), name='unique_ai_insight_source_title'),
        ),
    ]
