# Generated by Django 4.2 on 2026-08-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='tasks_task_project_b78682_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='tasks_task_assigne_b3b2bc_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'priority'], name='tasks_task_project_7f8813_idx'),
        ),
        migrations.AddIndex(
            model_name='taskactivity',
            index=models.Index(fields=['task', 'created_at'], name='tasks_taska_task_id_88cdfc_idx'),
        ),
        migrations.AddIndex(
            model_name='taskactivity',
            index=models.Index(fields=['action'], name='tasks_taska_action_b899ab_idx'),
        ),
    ]
