# Generated by Django 4.2 on 2026-08-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_invoice_e2429a_idx',
            old_name='payments_pay_invoi_7e73cf_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_transac_8e9d99_idx',
            old_name='payments_pay_transac_9b2b4f_idx',
        ),
    ]
