# Generated by Django 4.2 on 2026-08-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='globalactivity',
            new_name='automation__organiz_27fd74_idx',
            old_name='automation__organiz_127c03_idx',
        ),
        migrations.RenameIndex(
            model_name='globalactivity',
            new_name='automation__source_013b96_idx',
            old_name='automation__source_9e557f_idx',
        ),
        migrations.RenameIndex(
            model_name='globalactivity',
            new_name='automation__target__489e8a_idx',
            old_name='automation__target__9efb8e_idx',
        ),
        migrations.RenameIndex(
            model_name='leadfollowup',
            new_name='automation__assigne_5782c5_idx',
            old_name='automation__assigne_10f2c9_idx',
        ),
        migrations.RenameIndex(
            model_name='leadfollowup',
            new_name='automation__lead_id_b761a5_idx',
            old_name='automation__lead_id_10a8c4_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowrule',
            new_name='automation__organiz_50c49c_idx',
            old_name='automation__organiz_f0df17_idx',
        ),
    ]
