# Generated by Django 5.2.17 on 2026-08-11 16:23

import clientflow.apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers_alter_user_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=clientflow.apps.users.models.profile_photo_upload_to,
            ),
        ),
    ]
