# Generated by Django 4.2 on 2026-08-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_in_organiz_be0f8a_idx',
            old_name='invoices_inv_organi_5d4c4b_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_in_client__d0ba52_idx',
            old_name='invoices_inv_client_40d6fb_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_in_due_dat_a8d8f9_idx',
            old_name='invoices_inv_due_dat_0debb2_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
