# Generated by Django 4.2 on 2026-08-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_workflow_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_8a7c6b_idx',
            old_name='notificatio_user_id_91e664_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_categor_e0e064_idx',
            old_name='notificatio_categor_6c55c6_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_target__dfbaf5_idx',
            old_name='notificatio_target__36fe73_idx',
        ),
    ]
