export const queryKeys = {
  leads: (filters: unknown) => ['leads', filters] as const,
  clients: (filters: unknown) => ['clients', filters] as const,
  projects: (filters: unknown) => ['projects', filters] as const,
  project: (id: number) => ['project', id] as const,
  tasks: (projectId: number) => ['tasks', projectId] as const,
  users: ['users'] as const,
  invoices: (filters: unknown) => ['invoices', filters] as const,
  invoice: (id: number) => ['invoice', id] as const,
  invoicePayments: (id: number) => ['invoice-payments', id] as const,
  payments: (filters: unknown) => ['payments', filters] as const,
  dashboard: ['dashboard'] as const,
  notifications: (filters: unknown) => ['notifications', filters] as const,
  notificationUnreadCount: ['notification-unread-count'] as const,
  workflowRules: ['workflow-rules'] as const,
  automationPreferences: ['automation-preferences'] as const,
  followUps: (filters: unknown) => ['follow-ups', filters] as const,
  activityFeed: (filters: unknown) => ['activity-feed', filters] as const,
  automationDashboardSummary: ['automation-dashboard-summary'] as const,
  analyticsDashboard: (filters: unknown) => ['analytics-dashboard', filters] as const,
};
