export const queryKeys = {
  leads: (filters: unknown) => ['leads', filters] as const,
  clients: (filters: unknown) => ['clients', filters] as const,
  projects: (filters: unknown) => ['projects', filters] as const,
  project: (id: number) => ['project', id] as const,
  tasks: (projectId: number) => ['tasks', projectId] as const,
  users: ['users'] as const,
  invoices: (filters: unknown) => ['invoices', filters] as const,
  invoice: (id: number) => ['invoice', id] as const,
  invoicePayments: (id: number) => ['invoice-payments', id] as const,
  payments: (filters: unknown) => ['payments', filters] as const,
  dashboard: ['dashboard'] as const,
  notifications: (filters: unknown) => ['notifications', filters] as const,
  notificationUnreadCount: ['notification-unread-count'] as const,
  workflowRules: ['workflow-rules'] as const,
  automationPreferences: ['automation-preferences'] as const,
  followUps: (filters: unknown) => ['follow-ups', filters] as const,
  activityFeed: (filters: unknown) => ['activity-feed', filters] as const,
  automationDashboardSummary: ['automation-dashboard-summary'] as const,
  analyticsDashboard: (filters: unknown) => ['analytics-dashboard', filters] as const,
  aiRevenueForecast: (filters: unknown) => ['ai-revenue-forecast', filters] as const,
  aiInsights: (filters: unknown) => ['ai-insights', filters] as const,
  aiPaymentRisks: (filters: unknown) => ['ai-payment-risks', filters] as const,
  aiClientHealth: (filters: unknown) => ['ai-client-health', filters] as const,
  aiProposals: (filters: unknown) => ['ai-proposals', filters] as const,
  aiProposal: (id: number | undefined) => ['ai-proposal', id] as const,
  aiLeadScore: (id: number | undefined) => ['ai-lead-score', id] as const,
  aiPaymentRisk: (id: number | undefined) => ['ai-payment-risk', id] as const,
  aiClientChurnRisk: (id: number | undefined) => ['ai-client-churn-risk', id] as const,
};
