# Generated by Django 4.2 on 2026-08-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activity',
            new_name='crm_activit_target__abab8b_idx',
            old_name='crm_activi_target_8cf6c7_idx',
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='crm_activit_action_f1123d_idx',
            old_name='crm_activi_action_8f8fca_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='crm_note_target__f801c8_idx',
            old_name='crm_note_target_590b0f_idx',
        ),
    ]
